pipelines:
  branches: # runs automatically when a commit is pushed to
    master: # master branch
      - step:
          name: Build
          runs-on:
            - self.hosted
            - windows
          clone:
            lfs: true
            depth: full
            skip-ssl-verify: true
          script:
            - cd ACMS_App
            - '& "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\amd64\msbuild.exe" -t:restore -p:RestorePackagesConfig=true'
            - $arg1 = "-p:Configuration=Release"
            - $arg2 = "-p:GenerateAppxPackageOnBuild=true"
            - '& "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\amd64\msbuild.exe" $arg1 $arg2'

  custom: # manually triggered pipelines
    build_release:
      - step:
          name: Build Release
          runs-on:
            - self.hosted
            - windows
          clone:
            lfs: true
            depth: full
            skip-ssl-verify: true
          script:
            - cd ACMS_App
            - '& "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\amd64\msbuild.exe" -t:restore -p:RestorePackagesConfig=true'
            - $arg1 = "-p:Configuration=Release"
            - $arg2 = "-p:GenerateAppxPackageOnBuild=true"
            - '& "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\amd64\msbuild.exe" $arg1 $arg2'
            - $MsixFolderName = (Get-Item "ACMS_Program_Planner\bin\x64\Release\net9.0-windows10.0.22621.0\win-x64\AppPackages\ACMS_Program_Planner_*").FullName
            - $MsixFullPath = (Get-Item "$MsixFolderName\ACMS_Program_Planner_*.msix").FullName
            - echo $MsixFullPath
            - '& "C:\Program Files\DigiCert\DigiCert Keylocker Tools\smctl.exe" sign --keypair-alias=key_1292405931 -d=SHA256 --verbose --config-file "C:\Program Files\DigiCert\DigiCert Keylocker Tools\pkcs11properties.cfg" --input "$MsixFullPath"'
            - cd $env:BITBUCKET_CLONE_DIR
            - xcopy /y $MsixFullPath .

          artifacts:
            - "*.msix"
