<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows10.0.22621.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.22621.0</TargetPlatformMinVersion>
    <RootNamespace>ACMS_Program_Planner</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platforms>x64</Platforms>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <PublishProfile>win-$(Platform).pubxml</PublishProfile>
    <UseWinUI>true</UseWinUI>
    <EnableMsixTooling>true</EnableMsixTooling>
    <Nullable>enable</Nullable>
	<AppContainerApplication>false</AppContainerApplication>
	<AppxPackage>true</AppxPackage>
	<ApplicationType>Windows Store</ApplicationType>
	<ApplicationTypeRevision>10.0</ApplicationTypeRevision>
	<WindowsTargetPlatformVersion>10.0</WindowsTargetPlatformVersion>
	<WindowsTargetPlatformMinVersion>10.0.22621.0</WindowsTargetPlatformMinVersion>

	<!-- Add version properties here -->
	<Version>1.0.20.0</Version>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="ProgramsPage.xaml" />
    <None Remove="ProgramTimeline.xaml" />
    <None Remove="RFIDPage.xaml" />
    <None Remove="SettingsPage.xaml" />
    <None Remove="StepsPage.xaml" />
    <None Remove="QRPage.xaml" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\SplashScreen.scale-200.png" />
    <Content Include="Assets\LockScreenLogo.scale-200.png" />
    <Content Include="Assets\Square150x150Logo.scale-200.png" />
    <Content Include="Assets\Square44x44Logo.scale-200.png" />
    <Content Include="Assets\Square44x44Logo.targetsize-24_altform-unplated.png" />
    <Content Include="Assets\StoreLogo.png" />
    <Content Include="Assets\Wide310x150Logo.scale-200.png" />
  </ItemGroup>

  <ItemGroup>
    <Manifest Include="$(ApplicationManifest)" />
  </ItemGroup>

  <!--
    Defining the "Msix" ProjectCapability here allows the Single-project MSIX Packaging
    Tools extension to be activated for this project even if the Windows App SDK Nuget
    package has not yet been restored.
  -->
  <ItemGroup Condition="'$(DisableMsixProjectCapabilityAddedByProject)'!='true' and '$(EnableMsixTooling)'=='true'">
    <ProjectCapability Include="Msix" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3351.48" />
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.26100.4188" />
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.7.250606001" />
    <PackageReference Include="QRCoder" Version="1.7.0" />
    <PackageReference Include="ScottPlot.WinUI" Version="5.0.55" />
    <PackageReference Include="System.IO.Ports" Version="9.0.6" />
    <PackageReference Include="System.Threading.Tasks" Version="4.3.0" />
  </ItemGroup>
  <ItemGroup>
    <Page Update="QRPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="RFIDPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="SettingsPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="ServicePlanPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="ProgramTimeline.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="ProgramsPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="StepsPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <PropertyGroup Label="Globals">
    <WebView2EnableCsWinRTProjection>True</WebView2EnableCsWinRTProjection>
  </PropertyGroup>

  <!--
    Defining the "HasPackageAndPublishMenuAddedByProject" property here allows the Solution
    Explorer "Package and Publish" context menu entry to be enabled for this project even if
    the Windows App SDK Nuget package has not yet been restored.
  -->
  <PropertyGroup Condition="'$(DisableHasPackageAndPublishMenuAddedByProject)'!='true' and '$(EnableMsixTooling)'=='true'">
    <HasPackageAndPublishMenu>true</HasPackageAndPublishMenu>
  </PropertyGroup>

  <!-- Publish Properties -->
  <PropertyGroup>
    <GenerateAppInstallerFile>True</GenerateAppInstallerFile>
    <AppxPackageSigningEnabled>True</AppxPackageSigningEnabled>
    <AppxPackageSigningTimestampDigestAlgorithm>SHA256</AppxPackageSigningTimestampDigestAlgorithm>
    <AppxAutoIncrementPackageRevision>False</AppxAutoIncrementPackageRevision>
    <AppxSymbolPackageEnabled>False</AppxSymbolPackageEnabled>
    <GenerateTestArtifacts>True</GenerateTestArtifacts>
    <AppxBundle>Auto</AppxBundle>
    <HoursBetweenUpdateChecks>0</HoursBetweenUpdateChecks>
    <SupportedOSPlatformVersion>10.0.22621.0</SupportedOSPlatformVersion>
	<AppxBundlePlatforms>x64</AppxBundlePlatforms>
	<PackageCertificateThumbprint>30537B051175DEC5D30E68BEBE3632C04BBD615B</PackageCertificateThumbprint>
	<AppxPackageDir>C:\Users\GMateus\Ipeco Holdings Ltd\Development Tools Library - Dokumente\Ipeco-Demo-Tools\</AppxPackageDir>
	<AppInstallerUri>\\pdm15\Software\SDrive\EMIRATES_DEMO</AppInstallerUri>
  </PropertyGroup>
</Project>